
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Madrid

font:
  - file: "gfonts://Roboto"
    id: big_font1
    size: 64
  - file: "gfonts://Roboto"
    id: big_font2
    size: 48

lvgl:
  style_definitions:
    - id: page_style      # choose an ID for your definition
      x: 0
      y: 0
      width: 100%
      height: 100%
      bg_color: black
      border_width: 0
      pad_all: 0
      radius: 0
  pages:
    - id: main_page
      widgets:
        - obj:
            styles: page_style
        # Hora grande arriba
        - label:
            id: display_time
            text: "00:00:00"
            align: TOP_MID
            text_font: big_font1
            y: 20

        # Fecha debajo
        - label:
            id: display_date
            text: "14/09/2025"
            align: TOP_MID
            text_font: big_font2
            y: 90


        